name: productAttributeValue
type: base
id: pbc_prodattval

fields:
  - name: product
    type: relation
    collectionId: pbc_prod000000
    minSelect: 0
    maxSelect: 1

  - name: active
    type: bool

  - name: attributeValue
    type: relation
    collectionId: pbc_attributev
    minSelect: 0
    maxSelect: 1
    required: true

  - name: created
    type: autodate
    onCreate: true
    onUpdate: false

  - name: updated
    type: autodate
    onCreate: true
    onUpdate: true
